apiVersion: v1
kind: Secret
metadata:
  namespace: anotherclass-544
  name: api-tester-5441-postgresql
  labels:
    part-of: k8s-anotherclass
    managed-by: kubectl
stringData:
  postgresql-info.yaml: |
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgresql:5431"
    username: "dev"
    password: "dev123"
