apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: level1-reviews
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
    - route:
        - destination:
            host: reviews
            subset: v2