apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ratings-request-timeout
spec:
  hosts:
    - ratings
  http:
    - route:
        - destination:
            host: ratings
            subset: v1
      timeout: 2s