apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anotherclass-544
  name: cust-5441
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: cust
    app: cust
    instance: cust-5441
    version: 5.0.0
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: k8s-anotherclass
      component: backend-server
      name: cust
      app: cust
      instance: cust-5441
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: k8s-anotherclass
        component: backend-server
        name: cust
        app: cust
        instance: cust-5441
        version: 5.0.0
    spec:
      containers:
        - name: cust-5441
          # 1pro는 본인의 dockerhub username으로 변경해 주세요.
          image: 1pro/api-tester:5.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: "50m"
              memory: "150Mi"
            limits:
              cpu: "100m"
              memory: "150Mi"
          envFrom:
            - configMapRef:
                name: cust-5441-properties
          env:
            - name: downward_env_pod-name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: downward_env_node-name
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: downward_env_pod-ip
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          startupProbe:
            httpGet:
              path: "/startup"
              port: 8080
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: secret-datasource
              mountPath: /usr/src/myapp/datasource
            - name: downward-api-pod-info
              mountPath: /usr/src/myapp/downward-api
      volumes:
        - name: secret-datasource
          secret:
            secretName: api-tester-5441-postgresql
        - name: downward-api-pod-info
          downwardAPI:
            items:
              - path: "metadata_labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "metadata_annotations"
                fieldRef:
                  fieldPath: metadata.annotations