apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ratings-request-timeout
spec:
  parentRefs:
    - group: ""
      kind: Service
      name: ratings
      port: 9080
  rules:
    - backendRefs:
        - name: ratings-v1
          port: 9080
      timeouts:
        request: 2000ms