apiVersion: v1
kind: Service
metadata:
  name: ratings-v1
  labels:
    app: ratings
    service: ratings
    version: v1
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: ratings
    version: v1