apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: gateway-jwt-signature
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
    - from:
      - source:
          requestPrincipals: ["*"]
#      to:
#        - operation:
#            notPaths: ["/login"]  # 이 경로는 예외