apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: gateway-jwt-signature
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "1pro"
      jwks: |
        {
          "keys":[
            {
              "kty":"RSA",
              "n":"AK-mW1IFr5TUrpBB6DuRWkiwrinW5OfyWyDlie-RuV7MmyMaTFESqitnSCx3H5GrMsBjLiqNz-TUvWAcNcr0FXGavN0JJ7__8VN6mlgxy67gsOyAQoEkOO0cvw-rk7UBI8PFHmwHwr_ejQF--sLnVfmi_3CBkGNlY1gZYphUI9Gag7EqFOaDXcA5-DEcHye7IrQEB79Dy2lOKjfxkgeRVIarPcz-iAPkFYSINGSAaeiupG6xy1UwZH0LrATuVQOq1AJYUHJsIwodKdm2ExrTFLDLtA8ocXiC1zQqHqGRCEPPK_ciClJmAKVo167XDS3FHn1djyhGhYE_Gpb9WB0KnpU",
              "e":"AQAB",
              "alg":"RS256",
              "use":"sig",
              "kid":"key01"
            }
          ]
        }