apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: anotherclass-544
  name: cust-5441-outlierdetection
spec:
  host: cust-5441
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 3s
        idleTimeout: 30m
      http:
        http1MaxPendingRequests: 1000
        http2MaxRequests: 3000
        maxConcurrentStreams: 1000
        maxRetries: 10
        idleTimeout: 30m
    outlierDetection:
      consecutive5xxErrors: 5
      consecutiveGatewayErrors: 5
      splitExternalLocalOriginErrors: true
      consecutiveLocalOriginFailures: 5
      minHealthPercent: 20
    loadBalancer:
      simple: ROUND_ROBIN
      warmup:
        duration: 60s
        minimumPercent: 10
        aggression: 1.0
  subsets:
    - name: cust
      labels:
        name: cust