apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: reviews-loadbalancer
spec:
  host: reviews
#  trafficPolicy:
#    loadBalancer:
#      simple: ROUND_ROBIN
#      warmup:
#        duration: 120s
#        minimumPercent: 5
#        aggression: 1.0
  subsets:
    - name: v1
      labels:
        version: v1